version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: erp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - erp_network

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: erp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - erp_network

  # ERP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp_app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://erp_user:erp_password@postgres:5432/erp_db
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - erp_network
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: erp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - erp_network

volumes:
  postgres_data:
  redis_data:

networks:
  erp_network:
    driver: bridge