[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  # اختَر واحدة:
  NODE_VERSION = "18.20.3"   # آمن مع Next 14
  # NODE_VERSION = "20"       # بديل LTS أحدث
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  DATABASE_URL = "postgresql://user:pass@localhost:5432/placeholder"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# لا تضيف أي redirects global للـ /* → /index.html في مشروع Next.js
# لو محتاج Redirects معينة، أضف قواعد محددة لمسارات بعينها فقط.

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
